version: '3.8'

services:
  db:
    image: postgres:15
    container_name: boiler-plate
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plate      
      POSTGRES_PASSWORD: plate 
      POSTGRES_DB: plate_db     
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: